#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# MADS Setup Script
# Generates secrets, writes .env, and starts infrastructure containers.
# ---------------------------------------------------------------------------

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env"
DOCKER_DIR="$PROJECT_ROOT/docker"

info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
err()   { echo -e "${RED}[ERROR]${NC} $*"; }

header() {
  echo ""
  echo -e "${BOLD}========================================${NC}"
  echo -e "${BOLD}  MADS — Mutual Aid Delivery System${NC}"
  echo -e "${BOLD}  Setup Script${NC}"
  echo -e "${BOLD}========================================${NC}"
  echo ""
}

# ---- System detection -----------------------------------------------------
detect_system() {
  ARCH="$(uname -m)"
  case "$ARCH" in
    aarch64|arm64) ARCH_LABEL="ARM64" ;;
    x86_64)        ARCH_LABEL="x86_64" ;;
    *)             ARCH_LABEL="$ARCH" ;;
  esac

  if [[ -f /proc/meminfo ]]; then
    RAM_KB=$(awk '/MemTotal/ {print $2}' /proc/meminfo)
    RAM_MB=$((RAM_KB / 1024))
    RAM_GB=$(awk "BEGIN {printf \"%.1f\", $RAM_MB/1024}")
  elif command -v sysctl &>/dev/null; then
    RAM_BYTES=$(sysctl -n hw.memsize 2>/dev/null || echo 0)
    RAM_MB=$((RAM_BYTES / 1024 / 1024))
    RAM_GB=$(awk "BEGIN {printf \"%.1f\", $RAM_MB/1024}")
  else
    RAM_GB="unknown"
  fi

  info "Architecture: ${BOLD}$ARCH_LABEL${NC}"
  info "RAM:          ${BOLD}${RAM_GB} GB${NC}"
}

# ---- Dependency checks ----------------------------------------------------
check_deps() {
  local missing=0

  for cmd in docker openssl; do
    if ! command -v "$cmd" &>/dev/null; then
      err "Required tool not found: ${BOLD}$cmd${NC}"
      missing=1
    else
      ok "$cmd found: $(command -v "$cmd")"
    fi
  done

  # docker compose (plugin or standalone)
  if docker compose version &>/dev/null; then
    ok "docker compose found (plugin)"
  elif command -v docker-compose &>/dev/null; then
    ok "docker-compose found (standalone)"
  else
    err "Required tool not found: ${BOLD}docker compose${NC}"
    missing=1
  fi

  if [[ $missing -ne 0 ]]; then
    err "Install missing dependencies and re-run this script."
    exit 1
  fi
}

# ---- Secret generation ----------------------------------------------------
generate_secret() {
  openssl rand -hex 32
}

# ---- .env creation --------------------------------------------------------
create_env() {
  if [[ -f "$ENV_FILE" ]]; then
    warn ".env already exists at $ENV_FILE"
    read -rp "Overwrite? [y/N] " answer
    if [[ ! "$answer" =~ ^[Yy]$ ]]; then
      info "Keeping existing .env — skipping generation."
      return 0
    fi
  fi

  info "Generating cryptographic secrets..."
  JWT_SECRET="$(generate_secret)"
  DEK="$(generate_secret)"
  HMAC_KEY="$(generate_secret)"
  ok "Secrets generated."

  # Optional Twilio credentials
  TWILIO_ACCOUNT_SID=""
  TWILIO_AUTH_TOKEN=""
  echo ""
  read -rp "Configure Twilio credentials now? (optional) [y/N] " tw_answer
  if [[ "$tw_answer" =~ ^[Yy]$ ]]; then
    read -rp "  TWILIO_ACCOUNT_SID: " TWILIO_ACCOUNT_SID
    read -rp "  TWILIO_AUTH_TOKEN:  " TWILIO_AUTH_TOKEN
  fi

  # Optional JotForm key
  JOTFORM_API_KEY=""
  read -rp "Configure JotForm API key now? (optional) [y/N] " jf_answer
  if [[ "$jf_answer" =~ ^[Yy]$ ]]; then
    read -rp "  JOTFORM_API_KEY: " JOTFORM_API_KEY
  fi

  cat > "$ENV_FILE" <<EOF
# Database
DATABASE_URL=postgres://safecare:safecare@localhost:5432/safecare

# Redis
REDIS_URL=redis://localhost:6379

# Security (generated by setup.sh — do not commit)
JWT_SECRET=$JWT_SECRET
DEK=$DEK
HMAC_KEY=$HMAC_KEY

# Twilio (optional for Phase 1)
TWILIO_ACCOUNT_SID=$TWILIO_ACCOUNT_SID
TWILIO_AUTH_TOKEN=$TWILIO_AUTH_TOKEN

# JotForm (optional)
JOTFORM_API_KEY=$JOTFORM_API_KEY

# Server
PORT=3001
HOST=0.0.0.0
NODE_ENV=development

# Dashboard
NEXT_PUBLIC_API_URL=http://localhost:3001
EOF

  chmod 600 "$ENV_FILE"
  ok ".env written to $ENV_FILE (mode 600)"
}

# ---- SOPS + age encryption (optional) ------------------------------------
setup_sops() {
  if ! command -v age &>/dev/null; then
    info "age not installed — skipping SOPS encryption setup."
    info "Install age (https://github.com/FiloSottile/age) to enable secret encryption."
    return 0
  fi

  echo ""
  read -rp "Set up SOPS + age encryption for secrets? [y/N] " sops_answer
  if [[ ! "$sops_answer" =~ ^[Yy]$ ]]; then
    return 0
  fi

  SECRETS_DIR="$PROJECT_ROOT/secrets"
  AGE_KEY_FILE="$SECRETS_DIR/age-key.txt"

  if [[ ! -f "$AGE_KEY_FILE" ]]; then
    info "Generating age key pair..."
    age-keygen -o "$AGE_KEY_FILE" 2>&1
    chmod 600 "$AGE_KEY_FILE"
    ok "Age key written to $AGE_KEY_FILE"
  else
    info "Age key already exists at $AGE_KEY_FILE"
  fi

  AGE_PUBLIC_KEY=$(awk '/public key:/ {print $NF}' "$AGE_KEY_FILE")
  info "Public key: $AGE_PUBLIC_KEY"

  if command -v sops &>/dev/null; then
    SECRETS_YAML="$SECRETS_DIR/secrets.yaml"
    cat > "$SECRETS_YAML" <<EOF
jwt_secret: "$JWT_SECRET"
dek: "$DEK"
hmac_key: "$HMAC_KEY"
twilio_account_sid: "$TWILIO_ACCOUNT_SID"
twilio_auth_token: "$TWILIO_AUTH_TOKEN"
jotform_api_key: "$JOTFORM_API_KEY"
EOF
    sops --encrypt --age "$AGE_PUBLIC_KEY" "$SECRETS_YAML" > "$SECRETS_DIR/secrets.enc.yaml"
    rm -f "$SECRETS_YAML"
    ok "Encrypted secrets written to secrets/secrets.enc.yaml"
  else
    warn "sops not installed — age key generated but secrets not encrypted."
    info "Install sops (https://github.com/getsops/sops) to encrypt secrets."
  fi
}

# ---- Start infrastructure -------------------------------------------------
start_infra() {
  echo ""
  read -rp "Start Postgres and Redis containers now? [Y/n] " start_answer
  if [[ "$start_answer" =~ ^[Nn]$ ]]; then
    info "Skipping container startup."
    return 0
  fi

  info "Starting infrastructure containers (dev mode)..."
  cd "$DOCKER_DIR"

  if docker compose version &>/dev/null; then
    docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d postgres redis
  else
    docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d postgres redis
  fi

  ok "Postgres and Redis are starting."
  info "Check status with: docker compose -f docker/docker-compose.yml ps"
}

# ---- Next steps -----------------------------------------------------------
print_next_steps() {
  echo ""
  echo -e "${BOLD}----------------------------------------${NC}"
  echo -e "${GREEN}${BOLD}  Setup complete!${NC}"
  echo -e "${BOLD}----------------------------------------${NC}"
  echo ""
  echo -e "  ${BOLD}Next steps:${NC}"
  echo ""
  echo -e "  1. Install dependencies:"
  echo -e "     ${BLUE}pnpm install${NC}"
  echo ""
  echo -e "  2. Run database migrations:"
  echo -e "     ${BLUE}pnpm db:migrate${NC}"
  echo ""
  echo -e "  3. Start the dev servers:"
  echo -e "     ${BLUE}pnpm dev${NC}"
  echo ""
  echo -e "  Dashboard: ${BLUE}http://localhost:3000${NC}"
  echo -e "  Backend:   ${BLUE}http://localhost:3001${NC}"
  echo ""
}

# ---- Main -----------------------------------------------------------------
main() {
  header
  detect_system
  echo ""
  check_deps
  echo ""
  create_env
  setup_sops
  start_infra
  print_next_steps
}

main "$@"
